name: 'Distil_XLSR_5_Custom_Trans_Layer_VIB_DKDLoss_MSE_noaudioaug_b16_randomstart_feb07_cosine_only'
model:
  teacher:
    name: 'W2V2_VIB'
    teacher_module_paths:

      - 'ssl_model.model.encoder.layers.1.final_layer_norm'
      - 'ssl_model.model.encoder.layers.4.final_layer_norm'
      - 'ssl_model.model.encoder.layers.7.final_layer_norm'
      

    teacher_module_ios:

      - 'False:True'
      - 'False:True'
      - 'False:True'
      

    pretrained_path: '/datad/hungdx/KDW2V-AASISTL/pretrained/vib_conf-5_gelu_acmccs_apr3_moreko_telephone_epoch22.pth'

    is_parallel: False

  student:
    name: 'Distil_XLSR_N_Trans_Layer_VIB'
    student_module_paths:

      - 'ssl_model.model.encoder.layers.0.final_layer_norm'
      - 'ssl_model.model.encoder.layers.2.final_layer_norm'
      - 'ssl_model.model.encoder.layers.4.final_layer_norm'
      
      
    student_module_ios:

      - 'False:True'
      - 'False:True'      
      - 'False:True'      

    kwargs:
      num_layers: 5 # 
      order: 'custom' # 'middle' for middle layers, 'first' for first layers, 'last' for last layers, "custom" for custom layers
      custom_order: [1, 2, 3, 4, 5] # 2, 3, 4, 5th layer

is_learning_rate_scheduler: True

learning_rate_scheduler:
  name: "MultiStepLR"
  params:
    milestones: [50, 70]
    gamma: 0.5
    verbose: True

train:

  learning_rate: 0.00001
  weight_decay: 0.00001
  batch_size: 16
  num_epochs: 300
  num_workers: 4
  amp: True
  teacher: True
  patience: 30
  seed: 22
  freeze_ssl_num_epoch: 0 # 0 for no freeze
  dataset: 'supcon_feb07'
  augment_mode: 'rawboost' # 'rawboost' for rawboost, 'audiomentations' for audiomentations
  algo: -1 # No augmentation
  student_resume: '' # Stateless training
  cross_entropy_loss_weight: [0.21, 0.79]
  is_kl_loss: False
  copy_weights: True
  wandb_project_name: 'ablation_study'
  model_to_save: 'ablation_study_runs'

criterion_weights: [1, 1, 1]

criterions:


  
  - key: 'CosineLoss'
    kwargs:
      student_module_path: 'ssl_model.model.encoder.layers.0.final_layer_norm'
      student_module_io: 'output'
      teacher_module_path: 'ssl_model.model.encoder.layers.1.final_layer_norm'
      teacher_module_io: 'output'


  
  - key: 'CosineLoss'
    kwargs:
      student_module_path: 'ssl_model.model.encoder.layers.2.final_layer_norm'
      student_module_io: 'output'
      teacher_module_path: 'ssl_model.model.encoder.layers.4.final_layer_norm'
      teacher_module_io: 'output'


  
  - key: 'CosineLoss'
    kwargs:
      student_module_path: 'ssl_model.model.encoder.layers.4.final_layer_norm'
      student_module_io: 'output'
      teacher_module_path: 'ssl_model.model.encoder.layers.7.final_layer_norm'
      teacher_module_io: 'output'
  
 
  