SysConfig:
  wandb_disabled: True
  wandb_project: 'ASV-Spoofing-AASIST-SSL-short'
  wandb_name: 'XLSR_AASIST, Rawboots DA 4 pre_emphasis'
  wandb_entity: 'hungdinhxdev'
  wandb_key: 'd0284ef2414fcc6df741459db8ad48645db5e92c'
  wandb_notes: 'lr=8*1e-4, ts_hidden=660, rand_seed=1234, pre-emphasis'

  # 1s dataset for training
  path_label_asv_spoof_2019_la_train: '/datad/hungdx/Rawformer-implementation-anti-spoofing/datasets/protocols/LA19.cm.train.trn_1s.txt'
  path_label_asv_spoof_2019_la_dev: '/datad/hungdx/Rawformer-implementation-anti-spoofing/datasets/protocols/ASVspoof2019.LA.cm.dev.trl1s.txt'

  # 1s dataset for training
  path_asv_spoof_2019_la_train: '/data/hungdx/Towards-Real-Time-Deepfake-Speech-Detection-in-Resource-Limited-Scenarios/datasets/LA19_train_1s'
  path_asv_spoof_2019_la_dev: '/data/hungdx/Towards-Real-Time-Deepfake-Speech-Detection-in-Resource-Limited-Scenarios/datasets/ASVspoof2019_LA_dev_1s'

  path_label_asv_spoof_2019_la_eval: '/datab/hungdx/KDW2V-AASISTL/protocols/ASVspoof_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt'
  path_asv_spoof_2019_la_eval: '/datab/hungdx/KDW2V-AASISTL/databases/ASVspoof2019_LA_eval'
  path_label_asv_spoof_2021_la_eval: '/datab/hungdx/KDW2V-AASISTL/eval-packages-ASVSpoof2021/keys/LA/CM/trial_metadata.txt'
  path_asv_spoof_2021_la_eval: '/datab/hungdx/KDW2V-AASISTL/databases/ASVspoof2021_LA_eval'


  path_label_asv_spoof_2021_df_eval: '/data/hungdx/Towards-Real-Time-Deepfake-Speech-Detection-in-Resource-Limited-Scenarios/datasets/prototcols/ASVspoof2021.DF.cm.eval.trl_1s.txt'
  path_asv_spoof_2021_df_eval: '/data/hungdx/Towards-Real-Time-Deepfake-Speech-Detection-in-Resource-Limited-Scenarios/datasets/My_ASVspoof2021_DF_eval_1s'
  path_label_asv_spoof_2021_la_eval_spec: True # Special case for DF21 eval dataset

  num_workers: 8
  model: XLSR_AASIST
  path_to_save_model: './aasist_runs/XLSR_AASIST_RawBoost4_freeze_last12'
  df21_score_save_path: './aasist_runs/XLSR_AASIST_RawBoost4_freeze_last12/scores/XLSR_AASIST_DF21_score.txt'
  la21_score_save_path: './aasist_runs/XLSR_AASIST_RawBoost4_freeze_last12/scores/XLSR_AASIST_LA21_score.txt'
  la19_score_save_path: './aasist_runs/XLSR_AASIST_RawBoost4_freeze_last12/scores/XLSR_AASIST_LA19_score.txt'

ExpConfig:
  is_pre_emphasis: False
  is_random_start: True
  include_non_speech: False # not include non-speech in training data

  random_seed: 1234
  pre_emphasis: 0.97
  sample_rate: 16000
  train_duration_sec: 1
  test_duration_sec: 1
  batch_size_train: 32
  batch_size_test: 800
  embedding_size: 64
  max_epoch: 100
  lr: 0.000001
  weight_decay: 0.00001
  lr_min: 0.000001
  transformer_hidden: 660
  allow_data_augmentation: False
  data_augmentation:
    - 'RawBoost4'
  kwargs:
    partial_freeze_layers:
      target_layers: ["encoder.layers.11", "encoder.layers.10", "encoder.layers.9", "encoder.layers.8", "encoder.layers.7", "encoder.layers.6", "encoder.layers.5", "encoder.layers.4", "encoder.layers.3", "encoder.layers.2", "encoder.layers.1", "encoder.layers.0"]
      non_target_layers: ["encoder.layers.23", "encoder.layers.22", "encoder.layers.21", "encoder.layers.20", "encoder.layers.19", "encoder.layers.18", "encoder.layers.17", "encoder.layers.16", "encoder.layers.15", "encoder.layers.14", "encoder.layers.13", "encoder.layers.12"]