SysConfig:
  wandb_disabled: True
  wandb_project: 'ASV-Spoofing-AASIST-SSL-short'
  wandb_name: 'XLSR_AASIST, Rawboots DA 4 pre_emphasis'
  wandb_entity: 'hungdinhxdev'
  wandb_key: 'd0284ef2414fcc6df741459db8ad48645db5e92c'
  wandb_notes: 'lr=8*1e-4, ts_hidden=660, rand_seed=1234, pre-emphasis'

  # 1s dataset for training
  path_label_asv_spoof_2019_la_train: '/datad/hungdx/Rawformer-implementation-anti-spoofing/datasets/protocols/LA19.cm.train.trn_1s.txt'
  path_label_asv_spoof_2019_la_dev: '/datad/hungdx/Rawformer-implementation-anti-spoofing/datasets/protocols/ASVspoof2019.LA.cm.dev.trl1s.txt'

  # 1s dataset for training
  path_asv_spoof_2019_la_train: '/datad/hungdx/Rawformer-implementation-anti-spoofing/datasets/LA19_train_1s'
  path_asv_spoof_2019_la_dev: '/datad/hungdx/Rawformer-implementation-anti-spoofing/datasets/ASVspoof2019_LA_dev_1s'

  path_label_asv_spoof_2019_la_eval: '/datab/hungdx/KDW2V-AASISTL/protocols/ASVspoof_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt'
  path_asv_spoof_2019_la_eval: '/datab/hungdx/KDW2V-AASISTL/databases/ASVspoof2019_LA_eval'
  path_label_asv_spoof_2021_la_eval: '/datab/hungdx/KDW2V-AASISTL/eval-packages-ASVSpoof2021/keys/LA/CM/trial_metadata.txt'
  path_asv_spoof_2021_la_eval: '/datab/hungdx/KDW2V-AASISTL/databases/ASVspoof2021_LA_eval'
  
  # 1s dataset for evaluation

  path_label_asv_spoof_2021_df_eval: '/datad/hungdx/Rawformer-implementation-anti-spoofing/datasets/protocols/ASVspoof2021.DF.cm.eval.trl_1s.txt'
  path_asv_spoof_2021_df_eval: '/datad/hungdx/Rawformer-implementation-anti-spoofing/datasets/My_ASVspoof2021_DF_eval_1s'
  path_label_asv_spoof_2021_la_eval_spec: True # Special case for DF21 eval dataset

  num_workers: 8
  model: XLSR_AASIST
  path_to_save_model: './runs/aasist_runs/XLSR_AASIST_RawBoost4'
  df21_score_save_path: './runs/aasist_runs/XLSR_AASIST_RawBoost4/scores/XLSR_AASIST_DA3_EMPHASIS_DF21new_score.txt'
  la21_score_save_path: './runs/aasist_runs/XLSR_AASIST_RawBoost4/scores/XLSR_AASIST_DA3_EMPHASIS_LA21_score.txt'
  la19_score_save_path: './runs/aasist_runs/XLSR_AASIST_RawBoost4/scores/XLSR_AASIST_DA3_EMPHASIS_LA19_score.txt'

ExpConfig:
  is_pre_emphasis: False
  is_random_start: True
  include_non_speech: False # not include non-speech in training data

  random_seed: 1234
  pre_emphasis: 0.97
  sample_rate: 16000
  train_duration_sec: 1
  test_duration_sec: 1
  batch_size_train: 32
  batch_size_test: 800
  embedding_size: 64
  max_epoch: 100
  lr: 0.000001
  weight_decay: 0.00001
  lr_min: 0.000001
  transformer_hidden: 660
  allow_data_augmentation: False
  data_augmentation:
    - 'RawBoost4'